name: ds_project

channels:
  - conda-forge
  - defaults

dependencies:
  - affine
  - anyio
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - blosc
  - boost-cpp
  - branca
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - contourpy
  - cryptography
  - curl
  - cycler
  - cykhash
  - cython
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - fiona
  - flit-core
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - giflib
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libcxx
  - libdap4
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libkml
  - liblapack
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - libpysal
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzip
  - libzlib
  - llvm-openmp
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - momepy
  - munch
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nb_conda_kernels
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pycparser
  - pygeos
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyrobuf
  - pyrosm
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-rapidjson
  - python_abi
  - pytz
  - pyzmq
  - rasterio
  - readline
  - requests
  - rioxarray
  - rtree
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - shapely
  - six
  - snappy
  - sniffio
  - snuggs
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - tzcode
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xarray
  - xerces-c
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd